version: "3.9"

services:
  api:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: empresas-api
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: empresas-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
